// frontend/src/views/Dashboard.vue
<template>
  <div>
    <div class="page-header">
      <div>
        <h2>대시보드</h2>
        <div class="subtitle">{{ currentWeek }} · {{ today }}</div>
      </div>
      <button class="btn btn-ghost btn-sm" @click="refresh" data-tooltip="데이터를 최신 상태로 갱신">
        <span class="material-symbols-outlined" style="font-size:16px;width:16px;height:16px">refresh</span>
        새로고침
      </button>
    </div>

    <div class="page-body">
      <!-- ① 목표 요약 카드 -->
      <div class="grid-4" style="margin-bottom:24px">
        <div class="card stat-accent stat-accent-blue" data-tooltip="등록된 전체 목표(Objective) 수" data-tooltip-pos="bottom">
          <div class="card-body stat-card">
            <span class="material-symbols-outlined stat-icon stat-icon-blue">assignment</span>
            <div class="stat-value">{{ objectives.length }}</div>
            <div class="stat-label">전체 목표</div>
          </div>
        </div>
        <div class="card stat-accent stat-accent-primary" data-tooltip="현재 진행 중인 목표 수" data-tooltip-pos="bottom">
          <div class="card-body stat-card">
            <span class="material-symbols-outlined stat-icon stat-icon-primary">sync</span>
            <div class="stat-value" style="color:var(--primary)">{{ inProgressCount }}</div>
            <div class="stat-label">진행중</div>
          </div>
        </div>
        <div class="card stat-accent stat-accent-green" data-tooltip="완료된 목표 수" data-tooltip-pos="bottom">
          <div class="card-body stat-card">
            <span class="material-symbols-outlined stat-icon stat-icon-green">check_circle</span>
            <div class="stat-value" style="color:var(--success)">{{ completedCount }}</div>
            <div class="stat-label">완료</div>
          </div>
        </div>
        <div class="card stat-accent stat-accent-red" data-tooltip="위험 상태의 목표 수 — 즉각적인 조치가 필요합니다" data-tooltip-pos="bottom">
          <div class="card-body stat-card">
            <span class="material-symbols-outlined stat-icon stat-icon-red">warning</span>
            <div class="stat-value" style="color:var(--danger)">{{ dangerCount }}</div>
            <div class="stat-label">위험</div>
          </div>
        </div>
      </div>

      <!-- ② 액션 패널 3종 -->
      <div class="grid-3" style="margin-bottom:24px;align-items:start">

        <!-- 미답변 질문 -->
        <div class="card action-panel">
          <div class="card-header">
            <div class="panel-title">
              <span class="panel-icon" style="background:#fff7ed;color:var(--orange)">
                <span class="material-symbols-outlined">forum</span>
              </span>
              미답변 질문
            </div>
            <span class="badge" :class="unansweredQuestions.length ? 'badge-orange' : 'badge-gray'">
              {{ unansweredQuestions.length }}건
            </span>
          </div>
          <div class="card-body panel-body">
            <div v-if="actionLoading" class="loading-center" style="padding:24px"><div class="spinner"></div></div>
            <div v-else-if="unansweredQuestions.length === 0" class="panel-empty">
              이번 주 미답변 질문이 없습니다 👍
            </div>
            <ul v-else class="panel-list">
              <li v-for="q in unansweredQuestions" :key="q.id" class="panel-item panel-item-link" @click="goToQuestion(q)">
                <div class="panel-item-main">{{ q.question }}</div>
                <div class="panel-item-sub">
                  <span class="badge badge-blue">{{ getTaskName(q.task_id) }}</span>
                  <span class="panel-goto">바로가기 →</span>
                </div>
              </li>
            </ul>
          </div>
        </div>

        <!-- 이슈 -->
        <div class="card action-panel">
          <div class="card-header">
            <div class="panel-title">
              <span class="panel-icon" style="background:#fff7ed;color:var(--warning)">
                <span class="material-symbols-outlined">construction</span>
              </span>
              이슈
            </div>
            <span class="badge" :class="weekIssues.length ? 'badge-yellow' : 'badge-gray'">
              {{ weekIssues.length }}건
            </span>
          </div>
          <div class="card-body panel-body">
            <div v-if="actionLoading" class="loading-center" style="padding:24px"><div class="spinner"></div></div>
            <div v-else-if="weekIssues.length === 0" class="panel-empty">
              이번 주 등록된 이슈가 없습니다 👍
            </div>
            <ul v-else class="panel-list">
              <li v-for="p in weekIssues" :key="p.id" class="panel-item panel-item-link" @click="goToIssue(p)">
                <div class="issue-text">{{ p.issue }}</div>
                <div class="panel-item-sub">
                  <span class="badge badge-blue">{{ getTaskName(p.task_id) }}</span>
                  <span v-if="p.assignee" class="badge badge-gray">{{ p.assignee }}</span>
                  <span class="panel-goto">바로가기 →</span>
                </div>
              </li>
            </ul>
          </div>
        </div>

        <!-- 미배정 과제 -->
        <div class="card action-panel">
          <div class="card-header">
            <div class="panel-title">
              <span class="panel-icon" style="background:#f0f4ff;color:var(--primary)">
                <span class="material-symbols-outlined">person_off</span>
              </span>
              미배정 과제
            </div>
            <span class="badge" :class="unassignedTasks.length ? 'badge-red' : 'badge-gray'">
              {{ unassignedTasks.length }}건
            </span>
          </div>
          <div class="card-body panel-body">
            <div v-if="actionLoading" class="loading-center" style="padding:24px"><div class="spinner"></div></div>
            <div v-else-if="unassignedTasks.length === 0" class="panel-empty">
              모든 과제에 담당자가 배정되어 있습니다 👍
            </div>
            <ul v-else class="panel-list">
              <li v-for="t in unassignedTasks" :key="t.id" class="panel-item panel-item-link" @click="goToTask(t)">
                <div class="panel-item-main">{{ t.name }}</div>
                <div class="panel-item-sub">
                  <span class="badge badge-blue">{{ t.id }}</span>
                  <span class="badge badge-gray">{{ getObjectiveName(t.objective_id) }}</span>
                  <span class="panel-goto">바로가기 →</span>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>

      <!-- ③ 목표 카드 목록 -->
      <div class="section-header" style="margin-bottom:12px">
        <span class="section-header-title">목표 현황</span>
      </div>
      <div v-if="loading" class="loading-center"><div class="spinner"></div></div>
      <div v-else-if="objectives.length === 0" class="empty-state">
        <span class="material-symbols-outlined empty-icon">assignment</span>
        <p>등록된 목표가 없습니다. 관리 도구에서 목표를 추가하세요.</p>
      </div>
      <div v-else class="grid-2" style="gap:16px">
        <div v-for="obj in objectives" :key="obj.id" class="card obj-card">
          <div class="card-header">
            <div class="flex-center gap-8" style="min-width:0;flex:1">
              <span class="obj-id-badge">{{ obj.id }}</span>
              <span class="obj-name">{{ obj.name }}</span>
            </div>
            <span :class="statusBadgeClass(obj.status)" style="flex-shrink:0">{{ obj.status }}</span>
          </div>
          <div class="card-body" style="padding:12px 16px">
            <div v-if="obj.key_results && obj.key_results.length > 0">
              <div class="section-title">Key Results <span class="text-muted">({{ obj.key_results.length }})</span></div>
              <div class="kr-list">
                <div v-for="kr in obj.key_results" :key="kr.id" class="kr-item">
                  <span class="badge badge-blue" style="width:36px;justify-content:center">{{ kr.id }}</span>
                  <span class="text-sm">{{ kr.name }}</span>
                </div>
              </div>
            </div>
            <div v-else class="text-sm text-muted">Key Results 없음</div>
          </div>
        </div>
      </div>

      <!-- ④ 파트원별 활동 현황 -->
      <div class="section-header section-header-toggle" style="margin-top:32px" @click="activityOpen = !activityOpen" data-tooltip="클릭하여 접기 / 펼치기" data-tooltip-pos="bottom">
        <span class="section-header-title">파트원별 활동 현황</span>
        <span class="material-symbols-outlined section-chevron" :class="{ open: activityOpen }">expand_more</span>
      </div>
      <div v-if="staffList.length === 0 && activityOpen" class="card" style="margin-top:12px">
        <div class="card-body text-muted text-sm">파트원 정보가 없습니다.</div>
      </div>
      <div v-else-if="activityOpen" class="card" style="margin-top:12px">
        <table>
          <thead>
            <tr>
              <th style="width:160px">파트원</th>
              <th>최근 이슈</th>
              <th style="width:130px" data-tooltip="배정된 과제 수 (누적)">담당 과제</th>
              <th style="width:130px" data-tooltip="등록한 이슈 수 (누적)">이슈 등록</th>
              <th style="width:130px" data-tooltip="Q&A에 달린 답변 수 (누적)">Q&A 답변</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="s in staffList" :key="s.id" style="cursor:default">
              <td style="vertical-align:middle">
                <div class="member-cell">
                  <span class="member-avatar">{{ s.name[0] }}</span>
                  <div>
                    <div class="member-name">{{ s.name }}</div>
                    <div class="member-role">{{ s.role }}</div>
                  </div>
                </div>
              </td>
              <td style="vertical-align:middle">
                <div v-if="latestIssueMap[s.name]" class="latest-issue">
                  <span class="badge badge-gray" style="flex-shrink:0">{{ latestIssueMap[s.name].week }}</span>
                  <span class="latest-issue-text">{{ truncate(latestIssueMap[s.name].issue, 60) }}</span>
                </div>
                <span v-else class="text-muted text-sm">—</span>
              </td>
              <td style="vertical-align:middle">
                <div class="stat-bar-row">
                  <span class="stat-num">{{ memberStatsMap[s.name]?.tasks ?? 0 }}</span>
                  <div class="stat-bar">
                    <div class="stat-fill stat-fill-blue" :style="{ width: barWidth(memberStatsMap[s.name]?.tasks, maxStats.tasks) }"></div>
                  </div>
                </div>
              </td>
              <td style="vertical-align:middle">
                <div class="stat-bar-row">
                  <span class="stat-num">{{ memberStatsMap[s.name]?.issues ?? 0 }}</span>
                  <div class="stat-bar">
                    <div class="stat-fill stat-fill-orange" :style="{ width: barWidth(memberStatsMap[s.name]?.issues, maxStats.issues) }"></div>
                  </div>
                </div>
              </td>
              <td style="vertical-align:middle">
                <div class="stat-bar-row">
                  <span class="stat-num">{{ memberStatsMap[s.name]?.answers ?? 0 }}</span>
                  <div class="stat-bar">
                    <div class="stat-fill stat-fill-green" :style="{ width: barWidth(memberStatsMap[s.name]?.answers, maxStats.answers) }"></div>
                  </div>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { RouterLink, useRouter } from 'vue-router'
import axios from 'axios'
import { parseIds } from '../utils/parseIds.js'

const router = useRouter()

const objectives = ref([])
const tasks      = ref([])
const staffList  = ref([])
const questions  = ref([])
const progressList = ref([])
const allProgressItems = ref([])
const allQuestions     = ref([])

const loading = ref(false)
const actionLoading = ref(false)
const activityOpen = ref(true)

const today = new Date().toLocaleDateString('ko-KR', { year: 'numeric', month: 'long', day: 'numeric', weekday: 'long' })

function getCurrentWeekNumber() {
  const d = new Date()
  const start = new Date(d.getFullYear(), 0, 1)
  return Math.ceil(((d - start) / 86400000 + start.getDay() + 1) / 7)
}
const currentWeek = `W${getCurrentWeekNumber()}`

// ── 목표 통계 ──
const inProgressCount = computed(() => objectives.value.filter(o => o.status === '진행중').length)
const completedCount  = computed(() => objectives.value.filter(o => o.status === '완료').length)
const dangerCount     = computed(() => objectives.value.filter(o => o.status === '위험').length)

// ── 액션 패널 데이터 ──
const unansweredQuestions = computed(() =>
  questions.value.filter(q => !q.answers || q.answers.length === 0)
)

const weekIssues = computed(() =>
  progressList.value.filter(p => p.issue && p.issue.trim())
)

const assignedTaskIds = computed(() => {
  const ids = new Set()
  staffList.value.forEach(s => {
    parseIds(s.selected_tasks).forEach(id => ids.add(id))
  })
  return ids
})

const unassignedTasks = computed(() =>
  tasks.value.filter(t => !assignedTaskIds.value.has(t.id))
)

// ── 팀원별 활동 통계 ──
const memberStatsMap = computed(() => {
  const map = {}
  staffList.value.forEach(s => {
    map[s.name] = {
      tasks:   parseIds(s.selected_tasks || '').length,
      issues:  allProgressItems.value.filter(p => p.assignee === s.name && p.issue?.trim()).length,
      answers: allQuestions.value.flatMap(q => q.answers || []).filter(a => a.answer_by === s.name).length,
    }
  })
  return map
})

const maxStats = computed(() => {
  const vals = Object.values(memberStatsMap.value)
  if (!vals.length) return { tasks: 1, issues: 1, answers: 1 }
  return {
    tasks:   Math.max(1, ...vals.map(v => v.tasks)),
    issues:  Math.max(1, ...vals.map(v => v.issues)),
    answers: Math.max(1, ...vals.map(v => v.answers)),
  }
})

function barWidth(val, max) {
  if (!val) return '0%'
  return `${Math.max(3, Math.round((val / max) * 100))}%`
}

const latestIssueMap = computed(() => {
  const map = {}
  staffList.value.forEach(s => {
    const items = allProgressItems.value
      .filter(p => p.assignee === s.name && p.issue?.trim())
      .sort((a, b) => {
        const wa = parseInt((a.week || 'W0').slice(1))
        const wb = parseInt((b.week || 'W0').slice(1))
        return wb - wa
      })
    map[s.name] = items[0] ? { week: items[0].week, issue: items[0].issue } : null
  })
  return map
})

function truncate(text, len) {
  if (!text) return ''
  const first = text.split('\n')[0].trim()
  return first.length > len ? first.slice(0, len) + '…' : first
}

// ── 헬퍼 ──
function getTaskName(taskId) {
  return tasks.value.find(t => t.id === taskId)?.name || taskId
}
function getObjectiveName(objectiveId) {
  return objectives.value.find(o => o.id === objectiveId)?.name || objectiveId
}
function statusBadgeClass(status) {
  return { '진행중': 'badge badge-blue', '완료': 'badge badge-green', '위험': 'badge badge-red' }[status] || 'badge badge-gray'
}

// ── 바로가기 네비게이션 ──
function goToQuestion(q) {
  router.push({ path: '/progress', query: { week: currentWeek, focusQuestion: q.id } })
}
function goToIssue(p) {
  router.push({ path: '/progress', query: { week: currentWeek, focusIssue: p.task_id } })
}
function goToTask(t) {
  router.push({ path: '/admin', query: { tab: 'task', focusTask: t.id } })
}

// ── 데이터 로드 ──
async function refresh() {
  loading.value = true
  actionLoading.value = true
  try {
    const [oRes, tRes, sRes] = await Promise.all([
      axios.get('/api/okrs'),
      axios.get('/api/tasks'),
      axios.get('/api/staff'),
    ])
    objectives.value = oRes.data
    tasks.value      = tRes.data
    staffList.value  = sRes.data

    const [qRes, pRes, allPRes, allQRes] = await Promise.all([
      axios.get('/api/qna/questions', { params: { week: currentWeek } }),
      axios.get('/api/progress',      { params: { week: currentWeek } }),
      axios.get('/api/progress'),
      axios.get('/api/qna/questions'),
    ])
    questions.value        = qRes.data
    progressList.value     = pRes.data
    allProgressItems.value = allPRes.data
    allQuestions.value     = allQRes.data
  } finally {
    loading.value = false
    actionLoading.value = false
  }
}

onMounted(refresh)
</script>

<style scoped>
/* ── 통계 카드 ── */
.stat-accent { border-top: 3px solid var(--outline); }
.stat-accent-blue    { border-top-color: var(--primary); }
.stat-accent-primary { border-top-color: #6366f1; }
.stat-accent-green   { border-top-color: var(--success); }
.stat-accent-red     { border-top-color: var(--danger); }
.stat-icon {
  font-size: 28px;
  font-variation-settings: 'FILL' 1, 'wght' 400, 'GRAD' 0, 'opsz' 24;
  width: 32px;
  height: 32px;
  margin-bottom: 8px;
  display: flex;
  align-items: center;
  justify-content: center;
}
.stat-icon-blue    { color: var(--primary); }
.stat-icon-primary { color: #6366f1; }
.stat-icon-green   { color: var(--success); }
.stat-icon-red     { color: var(--danger); }

/* ── 액션 패널 ── */
.action-panel { display: flex; flex-direction: column; }

.panel-title {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 14px;
  font-weight: 600;
  color: var(--text-primary);
}
.panel-icon {
  width: 28px; height: 28px;
  border-radius: var(--radius-sm);
  display: inline-flex; align-items: center; justify-content: center;
  flex-shrink: 0;
}
.panel-icon .material-symbols-outlined {
  font-size: 16px;
  width: 16px;
  height: 16px;
}

.panel-body {
  padding: 12px 16px !important;
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.panel-empty {
  font-size: 13px;
  color: var(--text-muted);
  text-align: center;
  padding: 16px 0;
}

.panel-list {
  list-style: none;
  display: flex;
  flex-direction: column;
  gap: 6px;
  margin: 0;
  padding: 0;
  max-height: 220px;
  overflow-y: auto;
}

.panel-item {
  display: flex;
  flex-direction: column;
  gap: 4px;
  padding: 8px 10px;
  background: var(--gray-50);
  border-radius: var(--radius-sm);
  border-left: 3px solid var(--outline);
}

.panel-item-main {
  font-size: 13px;
  color: var(--text-primary);
  line-height: 1.4;
  word-break: keep-all;
}

.issue-text {
  font-size: 13px;
  color: var(--text-primary);
  line-height: 1.4;
  word-break: keep-all;
  white-space: pre-wrap;
}

.panel-item-sub {
  display: flex;
  gap: 4px;
  flex-wrap: wrap;
}

.panel-item-link {
  cursor: pointer;
  transition: background 0.15s, border-color 0.15s;
}
.panel-item-link:hover {
  background: var(--primary-light);
  border-left-color: var(--primary);
}

.panel-goto {
  font-size: 11px;
  color: var(--text-muted);
  margin-left: auto;
  flex-shrink: 0;
  transition: color 0.15s;
}
.panel-item-link:hover .panel-goto { color: var(--primary); }

/* ── 팀원별 활동 현황 ── */
.member-cell { display: flex; align-items: center; gap: 10px; }
.member-avatar {
  width: 32px; height: 32px;
  border-radius: var(--radius-full);
  background: var(--primary-light); color: var(--primary);
  display: flex; align-items: center; justify-content: center;
  font-weight: 700; font-size: 14px; flex-shrink: 0;
}
.member-name { font-size: 14px; font-weight: 600; color: var(--text-primary); }
.member-role { font-size: 12px; color: var(--text-muted); margin-top: 1px; }

.stat-bar-row { display: flex; align-items: center; gap: 8px; }
.stat-num { font-size: 13px; font-weight: 600; color: var(--text-primary); min-width: 18px; text-align: right; }
.stat-bar { flex: 1; height: 6px; background: var(--gray-100); border-radius: var(--radius-full); overflow: hidden; }
.stat-fill { height: 100%; border-radius: var(--radius-full); transition: width 0.4s ease; }
.stat-fill-blue   { background: var(--primary); }
.stat-fill-orange { background: var(--orange); }
.stat-fill-green  { background: var(--success); }

.latest-issue { display: flex; align-items: center; gap: 8px; min-width: 0; }
.latest-issue-text {
  font-size: 13px;
  color: var(--text-secondary);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

/* ── 섹션 헤더 ── */
.section-header { display: flex; align-items: center; gap: 8px; }
.section-header-title {
  font-size: 13px;
  font-weight: 600;
  color: var(--text-muted);
  text-transform: uppercase;
  letter-spacing: 0.05em;
}
.section-header-toggle {
  cursor: pointer;
  user-select: none;
}
.section-header-toggle:hover .section-header-title { color: var(--text-primary); }
.section-chevron {
  font-size: 18px; width: 18px; height: 18px;
  color: var(--text-muted);
  transition: transform 0.2s;
  margin-left: auto;
}
.section-chevron.open { transform: rotate(180deg); }

/* ── 목표 카드 ── */
.obj-card { transition: box-shadow .2s, transform .15s; }
.obj-card:hover { box-shadow: var(--shadow-l2); transform: translateY(-1px); }

.obj-id-badge {
  display: inline-flex; align-items: center; justify-content: center;
  width: 34px; height: 34px;
  background: var(--primary-light); color: var(--primary);
  border-radius: var(--radius-md);
  font-weight: 700; font-size: 13px;
  flex-shrink: 0;
}
.obj-name {
  font-weight: 600; font-size: 14px;
  color: var(--text-primary);
  overflow: hidden; text-overflow: ellipsis; white-space: nowrap;
}

/* ── KR ── */
.section-title {
  font-size: 11px; font-weight: 600;
  color: var(--text-muted);
  text-transform: uppercase; letter-spacing: 0.04em;
  margin-bottom: 8px;
}
.kr-list { display: flex; flex-direction: column; gap: 4px; }
.kr-item {
  display: flex; align-items: center; gap: 8px;
  background: var(--gray-50);
  border-radius: var(--radius-sm);
  padding: 6px 10px;
}
</style>

// design-system/ui_kits/work-management/Dashboard.jsx
/* work-management UI Kit — Dashboard view */
const { useState: useDashState, useMemo } = React;

function Dashboard() {
  const D = window.KIT_DATA;
  const [qWeek, setQWeek] = useDashState('this');
  const [qStatus, setQStatus] = useDashState('unanswered');
  const [issWeek, setIssWeek] = useDashState('this');
  const [actWeek, setActWeek] = useDashState('this');
  const [qOpen, setQOpen] = useDashState(false);
  const [issOpen, setIssOpen] = useDashState(false);
  const [activityOpen, setActivityOpen] = useDashState(true);
  const [matrixOpen, setMatrixOpen] = useDashState(true);
  const [modal, setModal] = useDashState(null); // {type, item}

  const weekOf = sel => (sel === 'last' ? D.lastWeek : D.currentWeek);

  // flat task rows (sub-tasks flattened)
  const flatRows = useMemo(() => {
    const rows = [];
    D.tasks.forEach(t => {
      if (t.sub_tasks && t.sub_tasks.length) t.sub_tasks.forEach(st => rows.push({ id: st.id, selfName: st.name, parentName: t.name }));
      else rows.push({ id: t.id, selfName: t.name, parentName: null });
    });
    return rows;
  }, []);

  function taskName(id) {
    const direct = D.tasks.find(t => t.id === id);
    if (direct) return direct.name;
    for (const t of D.tasks) { const st = (t.sub_tasks || []).find(s => s.id === id); if (st) return `${t.name} › ${st.name}`; }
    return id;
  }

  const unanswered = D.questions.filter(q => !q.answers.length);
  const weekIssues = D.issues.filter(i => i.week === D.currentWeek);
  const confThisWeek = flatRows.filter(r => D.confluence.some(c => c.task_id === r.id && c.week === D.currentWeek)).length;

  const filteredQ = D.questions.filter(q => q.week === weekOf(qWeek)).filter(q =>
    qStatus === 'answered' ? q.answers.length : qStatus === 'all' ? true : !q.answers.length);
  const filteredIss = D.issues.filter(i => i.week === weekOf(issWeek));

  // member stats
  const memberStats = useMemo(() => {
    const w = weekOf(actWeek);
    const map = {};
    D.staff.forEach(s => {
      const received = D.questions.filter(q => q.week === w && q.targets.includes(s.name));
      const answered = received.filter(q => q.answers.length).length;
      map[s.name] = {
        tasks: (s.task_ids || []).length,
        issues: D.issues.filter(i => i.week === w && i.assignee === s.name).length,
        answered, unanswered: received.length - answered,
      };
    });
    return map;
  }, [actWeek]);
  const maxTasks = Math.max(1, ...D.staff.map(s => memberStats[s.name].tasks));
  const maxIssues = Math.max(1, ...D.staff.map(s => memberStats[s.name].issues));

  function matrixCell(rowId, w) {
    const conf = D.confluence.some(c => c.task_id === rowId && c.week === w);
    const iss = D.issues.some(i => i.task_id === rowId && i.week === w);
    const qn = D.questions.filter(q => q.task_id === rowId && q.week === w).length;
    return { conf, iss, qn };
  }

  const strip = t => (t || '').replace(/<[^>]+>/g, '').replace(/\*\*/g, '');

  return (
    <div>
      <div className="page-header">
        <div>
          <h2>대시보드</h2>
          <div className="subtitle">{D.currentWeek} · 2026년 5월 21일 목요일</div>
        </div>
        <Button variant="ghost" size="sm" icon="refresh">새로고침</Button>
      </div>

      <div className="page-body">
        {/* KPIs */}
        <div className="grid-3" style={{ marginBottom: 24 }}>
          <Card className={'stat-accent ' + (unanswered.length ? 'stat-accent-orange' : 'stat-accent-green')}>
            <div className="card-body stat-card">
              <Icon name="quiz" fill className={unanswered.length ? 'stat-icon stat-icon-orange' : 'stat-icon stat-icon-green'} size={28} />
              <div className="stat-value" style={{ color: unanswered.length ? 'var(--orange)' : 'var(--success)' }}>{unanswered.length}</div>
              <div className="stat-label">미답변 의견/질문 (전체)</div>
            </div>
          </Card>
          <Card className={'stat-accent ' + (weekIssues.length ? 'stat-accent-yellow' : 'stat-accent-green')}>
            <div className="card-body stat-card">
              <Icon name="warning" fill className={weekIssues.length ? 'stat-icon stat-icon-yellow' : 'stat-icon stat-icon-green'} size={28} />
              <div className="stat-value" style={{ color: weekIssues.length ? 'var(--warning)' : 'var(--success)' }}>{weekIssues.length}</div>
              <div className="stat-label">이번 주 진행 현황 및 이슈</div>
            </div>
          </Card>
          <Card className="stat-accent stat-accent-blue">
            <div className="card-body stat-card">
              <Icon name="link" fill className="stat-icon stat-icon-blue" size={28} />
              <div className="stat-value" style={{ color: 'var(--primary)' }}>{confThisWeek}<span className="stat-denom">/{flatRows.length}</span></div>
              <div className="stat-label">컨플루언스 등록</div>
              <div className="stat-mini-bar"><div className="stat-mini-fill" style={{ width: Math.round(confThisWeek / flatRows.length * 100) + '%' }} /></div>
            </div>
          </Card>
        </div>

        {/* Notice */}
        <Card className="notice-card" style={{ marginBottom: 24 }}>
          <div className="card-header">
            <div className="panel-title">
              <span className="panel-icon" style={{ background: '#eff6ff', color: 'var(--primary)' }}><Icon name="campaign" size={16} /></span>
              파트 공지
            </div>
            <Button variant="ghost" size="xs">수정</Button>
          </div>
          <div className="card-body" style={{ padding: 16 }}>
            <div className="prose" dangerouslySetInnerHTML={{ __html: D.notice }} />
          </div>
        </Card>

        {/* Action panels */}
        <div className="grid-2" style={{ marginBottom: 24, alignItems: 'start' }}>
          <Card className="action-panel">
            <div className="card-header panel-header-toggle" onClick={() => setQOpen(!qOpen)}>
              <div className="panel-title">
                <span className="panel-icon" style={{ background: '#fff7ed', color: 'var(--orange)' }}><Icon name="forum" size={16} /></span>
                의견/질문
              </div>
              <div onClick={e => e.stopPropagation()}>
                <FilterGroup value={qWeek} onChange={setQWeek} options={[{ value: 'last', label: '지난주' }, { value: 'this', label: '이번주' }]} />
              </div>
              <div onClick={e => e.stopPropagation()}>
                <FilterGroup value={qStatus} onChange={setQStatus} options={[{ value: 'unanswered', label: '미답변' }, { value: 'answered', label: '답변완료' }, { value: 'all', label: '전체' }]} />
              </div>
              <Badge kind={filteredQ.length ? (qStatus === 'answered' ? 'green' : 'orange') : 'gray'}>{filteredQ.length}건</Badge>
              <Icon name="expand_more" className={'section-chevron' + (qOpen ? ' open' : '')} />
            </div>
            <div className="card-body panel-body">
              {filteredQ.length === 0 ? (
                <div className="panel-empty">{qStatus === 'answered' ? '답변 완료된 의견/질문이 없습니다' : '미답변 의견/질문이 없습니다 👍'}</div>
              ) : (
                <ul className={'panel-list' + (qOpen ? ' panel-list-expanded' : '')}>
                  {filteredQ.map(q => (
                    <li key={q.id} className="panel-item panel-item-link" onClick={() => setModal({ type: 'question', item: q })}>
                      <div className="q-targets-row">
                        <Badge kind="purple" style={{ fontSize: 11 }}>{q.questioner}</Badge>
                        <Icon name="arrow_forward" className="q-targets-icon" size={13} />
                        {q.targets.map(t => <span key={t} className="q-target-badge">{t}</span>)}
                      </div>
                      <div className="panel-item-main">{strip(q.question)}</div>
                      <div className="panel-item-sub">
                        <Badge kind="blue">{taskName(q.task_id)}</Badge>
                        <Badge kind="gray">{formatWeekLabel(q.week)}</Badge>
                        <span className="panel-goto">상세보기 →</span>
                      </div>
                    </li>
                  ))}
                </ul>
              )}
            </div>
          </Card>

          <Card className="action-panel">
            <div className="card-header panel-header-toggle" onClick={() => setIssOpen(!issOpen)}>
              <div className="panel-title">
                <span className="panel-icon" style={{ background: '#fff7ed', color: 'var(--warning)' }}><Icon name="construction" size={16} /></span>
                진행 현황 및 이슈
              </div>
              <div onClick={e => e.stopPropagation()}>
                <FilterGroup value={issWeek} onChange={setIssWeek} options={[{ value: 'last', label: '지난주' }, { value: 'this', label: '이번주' }]} />
              </div>
              <Badge kind={filteredIss.length ? 'yellow' : 'gray'}>{filteredIss.length}건</Badge>
              <Icon name="expand_more" className={'section-chevron' + (issOpen ? ' open' : '')} />
            </div>
            <div className="card-body panel-body">
              {filteredIss.length === 0 ? (
                <div className="panel-empty">등록된 진행 현황 및 이슈가 없습니다 👍</div>
              ) : (
                <ul className={'panel-list' + (issOpen ? ' panel-list-expanded' : '')}>
                  {filteredIss.map(p => (
                    <li key={p.id} className="panel-item panel-item-link" onClick={() => setModal({ type: 'issue', item: p })}>
                      <div className="panel-item-main">{strip(p.issue)}</div>
                      <div className="panel-item-sub">
                        <Badge kind="blue">{taskName(p.task_id)}</Badge>
                        <Badge kind="gray">{p.assignee}</Badge>
                        <span className="panel-goto">상세보기 →</span>
                      </div>
                    </li>
                  ))}
                </ul>
              )}
            </div>
          </Card>
        </div>

        {/* Side-by-side: activity + matrix */}
        <div className="side-panel-grid">
          <div className="side-panel-col">
            <div className="section-header section-header-toggle" onClick={() => setActivityOpen(!activityOpen)}>
              <span className="section-header-title">파트원별 활동 현황</span>
              <span className="panel-count-badge">파트원 {D.staff.length}명</span>
              <div onClick={e => e.stopPropagation()} style={{ marginLeft: 8 }}>
                <FilterGroup value={actWeek} onChange={setActWeek} options={[{ value: 'last', label: '지난주' }, { value: 'this', label: '이번주' }]} />
              </div>
              <Icon name="expand_more" className={'section-chevron' + (activityOpen ? ' open' : '')} />
            </div>
            {activityOpen && (
              <Card className="panel-card">
                <div className="activity-scroll">
                  <table>
                    <thead><tr><th>파트원</th><th>담당 과제</th><th>이슈</th><th>답변 현황</th></tr></thead>
                    <tbody>
                      {D.staff.map(s => {
                        const m = memberStats[s.name];
                        const tot = m.answered + m.unanswered;
                        return (
                          <tr key={s.username} style={{ cursor: 'default' }}>
                            <td style={{ verticalAlign: 'middle' }}>
                              <div className="member-cell"><Avatar name={s.name} /><div><div className="member-name">{s.name}</div><div className="member-role">{s.job_title}</div></div></div>
                            </td>
                            <td style={{ verticalAlign: 'middle' }}><div className="stat-bar-row"><span className="stat-num">{m.tasks}</span><div className="stat-bar"><div className="stat-fill" style={{ width: barW(m.tasks, maxTasks), background: 'var(--primary)' }} /></div></div></td>
                            <td style={{ verticalAlign: 'middle' }}><div className="stat-bar-row"><span className="stat-num">{m.issues}</span><div className="stat-bar"><div className="stat-fill" style={{ width: barW(m.issues, maxIssues), background: 'var(--orange)' }} /></div></div></td>
                            <td style={{ verticalAlign: 'middle' }}><div className="stat-bar-row"><span className="stat-num" style={{ color: '#059669' }}>{m.answered}</span><div className="stat-bar stat-bar-dual"><div className="stat-fill" style={{ width: tot ? (m.answered / tot * 100) + '%' : 0, background: 'var(--success)' }} /><div className="stat-fill" style={{ width: tot ? (m.unanswered / tot * 100) + '%' : 0, background: '#f97316' }} /></div><span className="stat-num" style={{ color: '#f97316' }}>{m.unanswered}</span></div></td>
                          </tr>
                        );
                      })}
                    </tbody>
                  </table>
                </div>
              </Card>
            )}
          </div>

          <div className="side-panel-col">
            <div className="section-header section-header-toggle" onClick={() => setMatrixOpen(!matrixOpen)}>
              <span className="section-header-title">주간 등록 현황</span>
              <span className="panel-count-badge">과제 {flatRows.length}건</span>
              <div className="matrix-legend-inline">
                <Icon name="link" fill className="matrix-icon matrix-icon-link" size={13} /><span>컨플루언스</span>
                <Icon name="warning" fill className="matrix-icon matrix-icon-issue" size={13} /><span>이슈</span>
                <span className="matrix-count" style={{ minWidth: 16, height: 16, fontSize: 10 }}>N</span><span>질문</span>
              </div>
              <Icon name="expand_more" className={'section-chevron' + (matrixOpen ? ' open' : '')} />
            </div>
            {matrixOpen && (
              <Card className="panel-card" style={{ overflow: 'hidden' }}>
                <div className="matrix-wrap">
                  <table className="matrix-table">
                    <thead><tr><th className="matrix-task-th">과제</th>{D.weeks.map(w => <th key={w} className={'matrix-week-th' + (w === D.currentWeek ? ' matrix-col-current' : '')}>{formatWeekLabel(w)}</th>)}</tr></thead>
                    <tbody>
                      {flatRows.map(row => (
                        <tr key={row.id}>
                          <td className="matrix-task-td">{row.parentName && <span className="matrix-parent">{row.parentName} › </span>}{row.selfName}</td>
                          {D.weeks.map(w => {
                            const c = matrixCell(row.id, w);
                            const empty = !c.conf && !c.iss && !c.qn;
                            return (
                              <td key={w} className={'matrix-cell' + (w === D.currentWeek ? ' matrix-col-current' : '')}>
                                <div className="matrix-cell-icons">
                                  {c.conf && <Icon name="link" fill className="matrix-icon matrix-icon-link" size={14} />}
                                  {c.iss && <Icon name="warning" fill className="matrix-icon matrix-icon-issue" size={14} />}
                                  {c.qn > 0 && <span className="matrix-count">{c.qn}</span>}
                                  {empty && <span className="matrix-dot-no">–</span>}
                                </div>
                              </td>
                            );
                          })}
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </Card>
            )}
          </div>
        </div>

        {/* Objectives */}
        <div className="section-header" style={{ marginTop: 32, marginBottom: 12 }}>
          <span className="section-header-title">목표 현황</span>
        </div>
        <div className="grid-2" style={{ gap: 16 }}>
          {D.objectives.map(obj => (
            <Card key={obj.id} className="obj-card">
              <div className="card-header">
                <div className="flex-center gap-8" style={{ minWidth: 0, flex: 1 }}>
                  <span className="obj-id-badge">{obj.id}</span>
                  <span className="obj-name">{obj.name}</span>
                </div>
                <span className={statusBadgeClass(obj.status)} style={{ flexShrink: 0 }}>{obj.status}</span>
              </div>
              <div className="card-body" style={{ padding: '12px 16px' }}>
                <div className="kr-section-title">Key Results <span className="text-muted">({obj.key_results.length})</span></div>
                <div className="kr-list">
                  {obj.key_results.map(kr => (
                    <div key={kr.id} className="kr-item">
                      <Badge kind="blue" style={{ width: 40, justifyContent: 'center' }}>{kr.id}</Badge>
                      <span className="text-sm">{kr.name}</span>
                    </div>
                  ))}
                </div>
              </div>
            </Card>
          ))}
        </div>
      </div>

      {modal && <DetailModal modal={modal} taskName={taskName} onClose={() => setModal(null)} />}
    </div>
  );
}

function barW(v, max) { return !v ? '0%' : Math.max(3, Math.round(v / max * 100)) + '%'; }

function DetailModal({ modal, taskName, onClose }) {
  const it = modal.item;
  return (
    <Modal title={modal.type === 'issue' ? '진행 현황 및 이슈 상세' : '질문 상세'} onClose={onClose} width={580}
      footer={<><Button variant="ghost" size="sm" onClick={onClose}>닫기</Button><Button variant="primary" size="sm">진행현황에서 보기 →</Button></>}>
      <div className="modal-meta">
        <Badge kind="blue">{taskName(it.task_id)}</Badge>
        {it.assignee && <Badge kind="gray">{it.assignee}</Badge>}
        {it.questioner && <Badge kind="purple">{it.questioner}</Badge>}
        {it.targets && it.targets.map(t => <Badge key={t} kind="blue">{t}</Badge>)}
        <Badge kind="gray">{formatWeekLabel(it.week)}</Badge>
      </div>
      <div className="modal-body">
        {modal.type === 'issue' ? (
          <div className="prose">{it.issue}</div>
        ) : (
          <>
            <div className="prose" style={{ marginBottom: 16 }}>{it.question}</div>
            {it.answers.length ? (
              <>
                <div className="modal-a-label">답변</div>
                {it.answers.map(a => <div key={a.id} className="prose answer-block">{a.answer}</div>)}
              </>
            ) : <div className="no-answer">아직 답변이 없습니다.</div>}
          </>
        )}
      </div>
    </Modal>
  );
}

Object.assign(window, { Dashboard });
